/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:afead9a8-a12b-46ce-9062-0c42ce5fd0e4",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_gXY9jkHEp",
    "aws_user_pools_web_client_id": "6mg9a8m5nr7pjguu15j36ueqlv",
    "oauth": {}
};


export default awsmobile;
